version: "2.19.1"
services:
  nginx:
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
  posts:
    image: cvcircle/posts
    build:
      context: ./src/apps/posts
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node entry-points/server.js
  users:
    image: cvcircle/users
    build:
      context: ./src/apps/users
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node entry-points/server.js
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email kmaryam818@gmail.com --agree-tos --no-eff-email --force-renewal -d cv-circle.com  -d www.cv-circle.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: $FRONTEND_DIR
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: $BACKEND_DIR/dhparam/
      o: bind
