version: "2.19.1"
services:
  nginx:
    ports:
      - "3000:80"
      - "3001:80"
  posts:
    image: cvcircle/posts:dev
    build:
      context: ./src/apps/posts
      args:
        NODE_ENV: development
    volumes:
      - ./src/apps/posts/:/app:ro
      - /app/__test__
      - ./src/apps/posts/__test__/coverage:/app/__test__/coverage
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  users:
    image: cvcircle/users:dev
    build:
      context: ./src/apps/users
      args:
        NODE_ENV: development
    volumes:
      - ./src/apps/users/:/app:ro
      - /app/__test__
      - ./src/apps/users/__test__/coverage:/app/__test__/coverage
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
