version: "2.19.1"
services:
  zookeeper:
    volumes:
      - $PWD/src/apps/messaging/zookeeper/:/app
  posts:
    build: 
      context: ./src/apps/posts
      args: 
        NODE_ENV: development
    volumes:
      - ./src/apps/posts/:/app:ro
      - /app/__test__
      - /app/node_modules
    environment: 
      - NODE_ENV=development
    command: npm run dev
  users:
    build: 
      context: ./src/apps/users
      args: 
        NODE_ENV: development
    volumes:
      - ./src/apps/users/:/app:ro
      - /app/node_modules
    environment: 
      - NODE_ENV=development
    command: npm run dev