version: "2.19.1"
services:
  posts:
    build: ./src/apps/posts
    ports:
      - "3000:3000"
    env_file: 
      - ./src/apps/posts/.env
    restart: always
  users:
    build: ./src/apps/users
    ports:
      - "3001:3001"
    env_file: 
      - ./src/apps/users/.env
    restart: always
  redis:
    image: redis
    restart: always
