version: "2.19.1"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  redis:
    image: redis
    container_name: redis
    restart: always

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      - ./src/apps/messaging/broker/.env

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092

  kafka-connect:
    build: ./src/apps/messaging/kafka-connect
    container_name: kafka-connect
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8083:8083
    env_file:
      - ./src/apps/messaging/kafka-connect/.env
    volumes:
      - ./src/apps/messaging/kafka-connect/data:/var/lib/kafka/data
      - ./src/apps/messaging/kafka-connect/secrets:/etc/kafka/secrets
    command:
      - bash 
      - -c 
      - | 
        confluent-hub install --no-prompt redis/redis-enterprise-kafka:6.7.4 
        /etc/confluent/docker/run &
        /app/connector 8083
        sleep infinity

  posts:
    build: ./src/apps/posts
    depends_on:
      - kafka-connect
    links:
      - "broker:broker"
    ports:
      - "3000:3000"
    env_file: 
      - ./src/apps/posts/.env
    restart: always
    
  users:
    build: ./src/apps/users
    ports:
      - "3001:3001"
    env_file: 
      - ./src/apps/users/.env
    restart: always
