#!/bin/bash
replace_passwords() {
  local file="$1"
  sed -i "s|\\\$ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD|$ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD|g" "$file"
  sed -i "s|\\\$ZOOKEEPER_SSL_KEYSTORE_PASSWORD|$ZOOKEEPER_SSL_KEYSTORE_PASSWORD|g" "$file"
}

if ! [ -e "ssl" ]; then
  mkdir ssl
fi

if ! [ -e "ssl/ca-cert" ]; then
  # Set up Zookeeper security
  ./zookeeper-ssl-setup $ZK_PRIVATE_KEY $ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD $ZOOKEEPER_SSL_KEYSTORE_PASSWORD
  
  # Set up Zookeeper client security
  ./zookeeper-shell-ssl-setup $ZK_PRIVATE_KEY $ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD $ZOOKEEPER_SSL_KEYSTORE_PASSWORD
fi

# Replace passwords in the zookeeper.properties file
replace_passwords "zookeeper-client.properties"
# To run zookeeper-client: /bin/zookeeper-shell zookeeper:2182 -zk-tls-config-file zookeeper-client.properties
echo -e "Ready to receive connections!"