#!/bin/bash
openssl req -new -x509 -keyout ssl/ca-key -out ssl/ca-cert -days 3650 -subj "/C=US/ST=Oregon/L=Oregon/O=SSL/OU=CV Circle/CN=zookeeper" -passin pass:$1 -passout pass:$1
keytool -keystore ssl/kafka.zookeeper.truststore.jks -alias ca-cert -import -file ssl/ca-cert -keypass $2 -storepass $2 -noprompt
keytool -keystore ssl/kafka.zookeeper.keystore.jks -alias zookeeper -validity 3650 -genkey -keyalg RSA -ext SAN=dns:zookeeper -dname "CN=zookeeper,OU=CV Circle,O=SSL,C=US,ST=Oregon,L=Oregon" -keypass $3 -storepass $3
keytool -keystore ssl/kafka.zookeeper.keystore.jks -alias zookeeper -certreq -file ssl/ca-request-zookeeper -storepass $3
openssl x509 -req -CA ssl/ca-cert -CAkey ssl/ca-key -in ssl/ca-request-zookeeper -out ssl/ca-signed-zookeeper -days 3650 -CAcreateserial -passin pass:$1
keytool -keystore ssl/kafka.zookeeper.keystore.jks -alias ca-cert -import -file ssl/ca-cert -storepass $3 -noprompt
keytool -keystore ssl/kafka.zookeeper.keystore.jks -alias zookeeper -import -file ssl/ca-signed-zookeeper -storepass $3 -noprompt